name: Winery CI

on: [ push, pull_request ]

jobs:

  java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup caching dirs for local maven repo and for DB of successfully built hashversioned modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/successful-hashvers-java8
          key: ${{ runner.os }}-maven-java8-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-java8-
      - name: Determine affected Maven projects
        id: affected-projects
        shell: bash
        run: |
          mkdir -p "${HOME}/successful-hashvers-java8" || true
          mvn -P java pro.avodonosov:hashver-maven-plugin:1.6:projects-to-build -DdbDir="${HOME}/successful-hashvers-java8"
          echo "::set-output name=list::$(cat target/hashver-projects-to-build)" 
      - name: Build the affected Maven projects
        if: ${{ steps.affected-projects.outputs.list }}
        run: mvn -Pjava -B package -pl ${{ steps.affected-projects.outputs.list }} -am
      - name: Save successfull hashvers
        if: ${{ steps.affected-projects.outputs.list && success() }}
        run: cp -r target/hashver-db-additions/* "${HOME}/successful-hashvers-java8"

  java12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Setup caching dirs for local maven repo and for DB of successfully built hashversioned modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/successful-hashvers-java12
          key: ${{ runner.os }}-maven-java12-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-java12-
      - name: Determine affected Maven projects
        id: affected-projects
        shell: bash
        run: |
          mkdir -p "${HOME}/successful-hashvers-java12" || true
          mvn -P java pro.avodonosov:hashver-maven-plugin:1.6:projects-to-build -DdbDir="${HOME}/successful-hashvers-java12"
          echo "::set-output name=list::$(cat target/hashver-projects-to-build)"
      - name: Build the affected Maven projects
        if: ${{ steps.affected-projects.outputs.list }}
        run: mvn -Pjava -B package -pl ${{ steps.affected-projects.outputs.list }} -am
      - name: Save successfull hashvers
        if: ${{ steps.affected-projects.outputs.list && success() }}
        run: cp -r target/hashver-db-additions/* "${HOME}/successful-hashvers-java12"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Build with Maven
        run: mvn -Pfrontend -B package
